version: '3.4'

services:
  microservice.order.history.api:
    container_name: microservice.order.history.api
    image: ${DOCKER_REGISTRY-}microserviceorderhistoryapi
    build:
      context: .
      dockerfile: Microservice.Order.History.Api/Dockerfile
    ports: 
      - "29000:8080"
      - "29001:8081"
    environment: 
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: https://+:8081;http://+:8080
        ASPNETCORE_HTTPS_PORT: 8081   
        JWT_ISSUER: ${JWT_ISSUER}
        JWT_AUDIENCE: ${JWT_AUDIENCE}
        JWT_SYMMETRIC_SECURITY_KEY: ${JWT_SYMMETRIC_SECURITY_KEY}  
    networks:
      - ms-order-system  
  
networks:
  ms-order-system: 
    external: true